"""create initial schema

Revision ID: ae07b5f5d15f
Revises: 
Create Date: 2026-05-30 12:48:56.818403
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae07b5f5d15f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.Enum('style_reference', 'generated_image', 'download_archive', name='fileassetpurpose'), nullable=False),
    sa.Column('storage_backend', sa.Enum('local', 'qiniu', name='storagebackend'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('byte_size > 0', name='ck_file_assets_byte_size_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_file_assets_purpose'), 'file_assets', ['purpose'], unique=False)
    op.create_index(op.f('ix_file_assets_storage_backend'), 'file_assets', ['storage_backend'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('auth_provider_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'disabled', name='stylestatus'), nullable=False),
    sa.Column('generation_profile_key', sa.String(length=120), nullable=True),
    sa.Column('style_prompt', sa.Text(), nullable=False),
    sa.Column('cover_asset_id', sa.String(length=32), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['file_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_styles_generation_profile_key'), 'styles', ['generation_profile_key'], unique=False)
    op.create_index(op.f('ix_styles_name'), 'styles', ['name'], unique=True)
    op.create_index(op.f('ix_styles_status'), 'styles', ['status'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=False),
    sa.Column('display_title', sa.String(length=120), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('image_count_mode', sa.Enum('auto', 'fixed', name='imagecountmode'), nullable=False),
    sa.Column('requested_image_count', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.String(length=32), nullable=False),
    sa.Column('style_name_snapshot', sa.String(length=80), nullable=False),
    sa.Column('style_prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('generation_profile_key_snapshot', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial_succeeded', 'failed', 'cancel_requested', 'cancelled', 'retrying', name='taskstatus'), nullable=False),
    sa.Column('current_step', sa.Enum('segment_story', 'generate_panel_prompts', 'generate_images', 'package_download', name='generationstepname'), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_error_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(image_count_mode = 'auto' AND requested_image_count IS NULL) OR (image_count_mode = 'fixed' AND requested_image_count > 0)", name='ck_generation_tasks_image_count_mode'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_next_run_at'), 'generation_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_generation_tasks_owner_user_id'), 'generation_tasks', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_status'), 'generation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_generation_tasks_style_id'), 'generation_tasks', ['style_id'], unique=False)
    op.create_table('style_reference_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('style_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['file_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'asset_id')
    )
    op.create_index(op.f('ix_style_reference_images_style_id'), 'style_reference_images', ['style_id'], unique=False)
    op.create_table('style_tests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('style_id', sa.String(length=32), nullable=False),
    sa.Column('test_text', sa.Text(), nullable=False),
    sa.Column('style_prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('generation_profile_key_snapshot', sa.String(length=120), nullable=True),
    sa.Column('composed_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancel_requested', 'cancelled', 'retrying', name='workflowstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('output_asset_id', sa.String(length=32), nullable=True),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_error_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['output_asset_id'], ['file_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_tests_next_run_at'), 'style_tests', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_style_tests_style_id'), 'style_tests', ['style_id'], unique=False)
    op.create_table('generation_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.Enum('segment_story', 'generate_panel_prompts', 'generate_images', 'package_download', name='generationstepname'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', 'retrying', name='stepstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('output_ref', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_error_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_generation_steps_status'), 'generation_steps', ['status'], unique=False)
    op.create_index(op.f('ix_generation_steps_step_name'), 'generation_steps', ['step_name'], unique=False)
    op.create_index(op.f('ix_generation_steps_task_id'), 'generation_steps', ['task_id'], unique=False)
    op.create_table('task_downloads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'ready', 'failed', name='downloadstatus'), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_error_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status != 'ready' OR asset_id IS NOT NULL", name='ck_task_downloads_ready_asset'),
    sa.ForeignKeyConstraint(['asset_id'], ['file_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_downloads_status'), 'task_downloads', ['status'], unique=False)
    op.create_index(op.f('ix_task_downloads_task_id'), 'task_downloads', ['task_id'], unique=False)
    op.create_table('task_panels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('panel_order', sa.Integer(), nullable=False),
    sa.Column('original_text_segment', sa.Text(), nullable=False),
    sa.Column('prompt_status', sa.Enum('pending', 'generated', 'failed', name='promptstatus'), nullable=False),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_model_snapshot', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('panel_order > 0', name='ck_task_panels_panel_order_positive'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'panel_order')
    )
    op.create_index(op.f('ix_task_panels_task_id'), 'task_panels', ['task_id'], unique=False)
    op.create_table('generated_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('panel_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='generatedimagestatus'), nullable=False),
    sa.Column('final_prompt', sa.Text(), nullable=False),
    sa.Column('generation_profile_key_snapshot', sa.String(length=120), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_error_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status != 'succeeded' OR asset_id IS NOT NULL", name='ck_generated_images_succeeded_asset'),
    sa.ForeignKeyConstraint(['asset_id'], ['file_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['panel_id'], ['task_panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id')
    )
    op.create_index(op.f('ix_generated_images_task_id'), 'generated_images', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_images_task_id'), table_name='generated_images')
    op.drop_table('generated_images')
    op.drop_index(op.f('ix_task_panels_task_id'), table_name='task_panels')
    op.drop_table('task_panels')
    op.drop_index(op.f('ix_task_downloads_task_id'), table_name='task_downloads')
    op.drop_index(op.f('ix_task_downloads_status'), table_name='task_downloads')
    op.drop_table('task_downloads')
    op.drop_index(op.f('ix_generation_steps_task_id'), table_name='generation_steps')
    op.drop_index(op.f('ix_generation_steps_step_name'), table_name='generation_steps')
    op.drop_index(op.f('ix_generation_steps_status'), table_name='generation_steps')
    op.drop_table('generation_steps')
    op.drop_index(op.f('ix_style_tests_style_id'), table_name='style_tests')
    op.drop_index(op.f('ix_style_tests_next_run_at'), table_name='style_tests')
    op.drop_table('style_tests')
    op.drop_index(op.f('ix_style_reference_images_style_id'), table_name='style_reference_images')
    op.drop_table('style_reference_images')
    op.drop_index(op.f('ix_generation_tasks_style_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_status'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_owner_user_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_next_run_at'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index(op.f('ix_styles_status'), table_name='styles')
    op.drop_index(op.f('ix_styles_name'), table_name='styles')
    op.drop_index(op.f('ix_styles_generation_profile_key'), table_name='styles')
    op.drop_table('styles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_file_assets_storage_backend'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_purpose'), table_name='file_assets')
    op.drop_table('file_assets')
    # ### end Alembic commands ###
